# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  repository_dispatch:
    inputs:
      releaseName:
        description: 'Release name'
        required: true
        default: ''
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@master
        with:
          node-version: "16.x"

      - name: Setup Dependencies & Build
        run: |
          npm install
          npm run build
          tar -zcvf ./Bark-Chrome-Extension.tgz ./Bark-Chrome-Extension

      - uses: ncipollo/release-action@v1
        with:
          release_name: ${{ releaseName }}
          artifacts: "Bark-Chrome-Extension.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
